# Generated by Django 4.0.3 on 2022-03-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product_option', models.ForeignKey(on_delete=models.Model, related_name='carts', to='products.productoption')),
                ('user', models.OneToOneField(on_delete=models.Model, to='users.user')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
