# Generated by Django 4.0.3 on 2022-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(related_name='tags', to='products.product'),
        ),
    ]
